export const GET_PRODUCT_CATEGORIES_REQUEST = 'GET_PRODUCT_CATEGORIES_REQUEST'
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS'
export const GET_PRODUCT_CATEGORIES_FAILED = 'GET_PRODUCT_CATEGORIES_FAILED'
export const GET_PRODUCT_CATEGORIES_SUCCESSS = 'GET_PRODUCT_CATEGORIES_SUCCESSS'

export const SAVE_PRODUCT_CATEGORIES_REQUEST = 'SAVE_PRODUCT_CATEGORIES_REQUEST'
export const SAVE_PRODUCT_CATEGORIES_SUCCESS = 'SAVE_PRODUCT_CATEGORIES_SUCCESS'
export const SAVE_PRODUCT_CATEGORIES_FAILED = 'SAVE_PRODUCT_CATEGORIES_FAILED'

export const PRODUCT_TYPE_NAME_REQUEST = 'PRODUCT_TYPE_NAME_REQUEST'
export const PRODUCT_TYPE_NAME_SUCCESS = 'PRODUCT_TYPE_NAME_SUCCESS'
export const PRODUCT_TYPE_NAME_FAILED = 'PRODUCT_TYPE_NAME_FAILED'
export const UPDATE_PRODUCT_TYPE_NAME_SAVED_STATE = 'UPDATE_PRODUCT_TYPE_NAME_SAVED_STATE'

export const UPDATE_GPO_SAVED_STATE = 'UPDATE_GPO_SAVED_STATE'
