
export const GET_PRODUCT_CATEGORIES_REQUEST = 'GET_PRODUCT_CATEGORIES_REQUEST'
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS'
export const GET_PRODUCT_CATEGORIES_FAILED = 'GET_PRODUCT_CATEGORIES_FAILED'

export const SAVE_PRODUCT_CATEGORIES_REQUEST = 'SAVE_PRODUCT_CATEGORIES_REQUEST'
export const SAVE_PRODUCT_CATEGORIES_SUCCESS = 'SAVE_PRODUCT_CATEGORIES_SUCCESS'
export const SAVE_PRODUCT_CATEGORIES_FAILED = 'SAVE_PRODUCT_CATEGORIES_FAILED'

export const UPDATE_GPO_SAVED_STATE = 'UPDATE_GPO_SAVED_STATE'